// <auto-generated />
using AmusementPark.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AmusementPark.Migrations
{
    [DbContext(typeof(ParkContext))]
    [Migration("20250610120738_ConfigurePositionAsOwnedType")]
    partial class ConfigurePositionAsOwnedType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("AmusementPark.Models.Park", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Budget")
                        .HasColumnType("REAL");

                    b.Property<string>("GridParkJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("InventoryBuildingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlacedBuildingJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalVisitors")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VisitorInPark")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VisitorsEntry")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VisitorsOut")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Parks");
                });
#pragma warning restore 612, 618
        }
    }
}
